Output Issuer ID instead of [object Object].
credential-handler/chapi-demo-wallet pull request #16
Opened 2023-08-14 19:15 UTC by BigBlueHat

Fixes #14.

Not a thorough fix--as the ID is pretty paltry in terms of data, but it at least looks better than `[object Object]`.

2023-08-15 20:30 UTC, dlongley requested changes

2023-08-15 20:30 UTC, dlongley commented on wallet-ui-store.html
> +    document.getElementById('credentialIssuer').innerHTML = vc.issuer.id;
Hmm, needs to be more like:

```suggestion
    document.getElementById('credentialIssuer').innerHTML = vc.issuer.id ?? vc.issuer;
```

`issuer` can be a string with the ID value or an object that MUST have an `id` property with the ID as the value.

2023-08-15 21:05 UTC, BigBlueHat commented
@dlongley good catch! Sorry I missed that. Fixed now.

2023-08-15 21:06 UTC, dlongley approved these changes

2023-08-15 21:07 UTC, dlongley commented
Also, this will need a CHANGELOG entry.

2023-08-16 13:31 UTC, BigBlueHat commented
@dlongley added a changelog entry. If you're cool with it, let me know or just merge. 😃

2023-08-16 16:14 UTC, dlongley approved these changes

2023-08-16 16:14 UTC, dlongley commented on CHANGELOG.md
> +## 2.0.4 - 2023-08-16
JFYI, this has to be set right before running the tools (the tool needs to see an uncommitted change in the changelog, where we put the release date), so we typically just leave a placeholder for the day until release time.

```suggestion
## 2.0.4 - 2023-08-dd
```

2023-08-16 16:14 UTC, merged